import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync} from 'node:fs';
const id=JSON.parse(readFileSync('artifacts/paris434-shot-job.json','utf8')).id;

test('selected loss photo aligns beside video, marks racket gap and pages technical evidence by five',async({page,request})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto(`/review/${id}`);
  const loss=page.getByRole('region',{name:'Lost rally review'});
  await loss.getByRole('button',{name:'Loss 2 · 81.5 s',exact:true}).click();
  const photo=loss.getByRole('figure',{name:'Exact attempt photo'});
  expect((await photo.boundingBox())!.width).toBeLessThanOrEqual(160);
  await photo.getByText('Why this photo?',{exact:true}).click();
  await expect(photo).toContainText('relative to player height');
  await expect(photo).toContainText('not a confirmed ground-touch');
  await photo.getByText('Why this photo?',{exact:true}).click();
  await expect(photo).toContainText('80.533 s · frame 2416');
  await expect.poll(()=>photo.locator('img').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBe(1280);
  await expect(photo.locator('[data-attempt-distance]')).toHaveAttribute('data-attempt-distance','wrist-proxy');
  const videoBox=(await page.locator('.review-camera video').boundingBox())!;
  const sidebarBox=(await page.locator('.review-sidebar').boundingBox())!;
  expect(sidebarBox.x).toBeGreaterThan(videoBox.x+videoBox.width);
  expect(Math.abs(sidebarBox.y-videoBox.y)).toBeLessThan(3);
  const heatmapBox=(await page.locator('.review-heatmap').boundingBox())!;
  expect(heatmapBox.x).toBeGreaterThan(videoBox.x+videoBox.width);
  expect(heatmapBox.y).toBeGreaterThanOrEqual(0);
  expect(heatmapBox.y+heatmapBox.height).toBeLessThan(1000);
  await loss.getByRole('button',{name:'Show attempt at 80.533 s',exact:true}).click();
  await expect.poll(()=>page.locator('.review-camera video').evaluate((v:HTMLVideoElement)=>!v.seeking&&v.readyState>=2&&v.paused)).toBe(true);
  expect((await request.get(`/api/analysis/${id}/frames/2416`)).headers()['content-type']).toBe('image/jpeg');
  expect((await request.get(`/api/analysis/${id}/frames/0`)).status()).toBe(404);
  await photo.getByRole('button',{name:'Mark racket head',exact:true}).click();
  const imageButton=photo.getByRole('button',{name:'Mark racket head on attempt photo'});
  const box=(await imageButton.boundingBox())!;
  await imageButton.click({position:{x:box.width*.6,y:box.height*.7}});
  await expect(photo.locator('[data-attempt-distance]')).toHaveAttribute('data-attempt-distance','manual-racket');
  await expect(photo).toContainText('Manually marked racket head');
  const marker=photo.locator('[data-attempt-distance] line');
  const previousX=Number(await marker.getAttribute('x1'));
  await imageButton.focus();await page.keyboard.press('ArrowRight');
  expect(Number(await marker.getAttribute('x1'))).toBeCloseTo(previousX+5,5);
  await page.reload();await loss.getByRole('button',{name:'Loss 2 · 81.5 s',exact:true}).click();
  await expect(photo.locator('[data-attempt-distance]')).toHaveAttribute('data-attempt-distance','manual-racket');
  await photo.getByRole('button',{name:'Reset racket mark'}).click();
  await page.getByText('Technical details: shots, poses & rally boundaries',{exact:true}).click();
  await page.getByRole('button',{name:'Hit poses',exact:true}).click();
  const poses=page.getByRole('region',{name:'Near-side hit poses'});
  await expect(poses.locator('tbody tr')).toHaveCount(5);
  const first=await poses.locator('tbody tr').first().innerText();
  await poses.getByRole('navigation',{name:'Pose pages'}).getByRole('button',{name:'Next'}).click();
  await expect(poses.locator('tbody tr')).toHaveCount(5);
  expect(await poses.locator('tbody tr').first().innerText()).not.toBe(first);
  await poses.getByRole('navigation',{name:'Pose pages'}).getByRole('button',{name:'Previous'}).click();
  expect(await poses.locator('tbody tr').first().innerText()).toBe(first);
  await page.getByRole('button',{name:'Shot types',exact:true}).click();
  const shots=page.getByRole('region',{name:'Shot contacts'});
  await expect(shots.locator('tbody tr')).toHaveCount(5);
  await shots.getByRole('navigation',{name:'Contact pages'}).getByRole('button',{name:'Next'}).click();
  expect(await shots.locator('tbody tr').count()).toBeLessThanOrEqual(5);
  await expect(page.getByRole('region',{name:'Possible shuttle landings'})).toHaveCount(0);
  await expect(page.getByRole('region',{name:'Near-player ending review'})).toHaveCount(0);
  await page.getByText('Technical details: shots, poses & rally boundaries',{exact:true}).click();
  await page.screenshot({path:'artifacts/paris434-compact-loss.png',fullPage:true});
  expect((await new AxeBuilder({page}).include('main').analyze()).violations).toEqual([]);
  for(const width of [320,768]) {await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}
  expect(errors).toEqual([]);
});
