import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFileSync } from 'node:fs';

test('Paris near-court lines and hit-pose frames are visible without LLM', async ({ page, request }) => {
  test.setTimeout(600_000);
  const manifest = JSON.parse(readFileSync('artifacts/paris434-near-job.json','utf8'));
  await expect.poll(async () => (await (await request.get(`/api/analysis/${manifest.id}`)).json()).status, {timeout:570_000,intervals:[3000]}).toBe('complete');
  const data = (await (await request.get(`/api/analysis/${manifest.id}`)).json()).result;
  expect(data.fileName).toMatch(/350_434\.mp4$/);
  expect(data.options.pose).toBe(true); expect(data.options.llm).toBe(false);
  expect(data.metrics.farPoses).toBe(0);
  expect(data.hitPoses.length).toBeGreaterThan(0);
  expect(data.courtLines.method).toBe('original_pixel_contrast_line_fit_v2');
  expect(data.courtLines.segments).toHaveLength(3);
  for (const segment of data.courtLines.segments) expect(segment.lines).toHaveLength(8);
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => {if(m.type()==='error') errors.push(m.text());});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto(`/review/${manifest.id}`);
  await expect(page.getByLabel('Near-side court lines')).toBeChecked();
  await expect(page.locator('[data-court-line]')).toHaveCount(8);
  await page.getByLabel('Near-side court lines').uncheck();
  await expect(page.locator('[data-court-line]')).toHaveCount(0);
  await page.getByLabel('Near-side court lines').check();
  const region = page.getByRole('region',{name:'Near-side hit poses'});
  await expect(region).toContainText('Raised arm means the wrist is above the shoulder');
  const event = data.hitPoses.find((e: {status:string;pose:string}) => e.status==='estimated_contact' && e.pose!=='Pose uncertain') ?? data.hitPoses[0];
  await region.getByRole('button',{name:`Show pose at ${event.time.toFixed(3)} s · frame ${event.frame}`,exact:true}).click();
  const video = page.locator('.review-camera video');
  await expect.poll(async () => video.evaluate(v => Math.abs(v.getBoundingClientRect().top))).toBeLessThan(2);
  await expect.poll(async () => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeCloseTo(event.time,2);
  expect(await video.evaluate((v: HTMLVideoElement) => v.paused)).toBe(true);
  await expect(page.locator('.review-camera svg g').filter({has:page.locator('rect')})).toHaveCount(1);
  await page.screenshot({path:'artifacts/paris434-near-review.png',fullPage:true});
  await region.getByRole('button',{name:`Replay pose at ${event.time.toFixed(3)} s`,exact:true}).click();
  await expect.poll(async () => video.evaluate(v => Math.abs(v.getBoundingClientRect().top))).toBeLessThan(2);
  await expect.poll(async () => video.evaluate((v: HTMLVideoElement, e: {time:number}) => ({paused:v.paused,done:v.currentTime>=e.time+.6}), event)).toEqual({paused:true,done:true});
  await video.evaluate(async (v: HTMLVideoElement) => { v.pause(); v.currentTime=24; });
  await expect(page.locator('[data-court-line]')).toHaveCount(0);
  const heatmap = page.locator('.review-heatmap');
  const heat = () => heatmap.locator('rect title').allTextContents();
  await expect.poll(async () => (await heat()).length).toBeGreaterThan(0);
  const laterHeat = await heat();
  await video.evaluate((v: HTMLVideoElement) => { v.currentTime=0; });
  await expect.poll(heat).toEqual([]);
  await video.evaluate((v: HTMLVideoElement) => { v.currentTime=24; });
  await expect.poll(heat).toEqual(laterHeat);
  await video.evaluate(async (v: HTMLVideoElement) => { v.currentTime=2; await v.play(); });
  const earlyHeat = await heat();
  await expect.poll(heat).not.toEqual(earlyHeat);
  await video.evaluate((v: HTMLVideoElement) => v.pause());
  const download = page.waitForEvent('download');
  await page.getByRole('button',{name:'Download reviewed JSON'}).click();
  const saved = await download; const exported = JSON.parse(readFileSync((await saved.path())!,'utf8'));
  expect(exported.hitPoses).toEqual(data.hitPoses); expect(exported.courtLines).toEqual(data.courtLines);
  await expect(page.getByRole('region',{name:'Before-landing coaching'})).toHaveCount(0);
  expect((await new AxeBuilder({page}).include('.analysis-review').analyze()).violations).toEqual([]);
  await page.setViewportSize({width:390,height:844});
  await page.emulateMedia({reducedMotion:'no-preference'});
  await region.getByRole('button',{name:/^Show pose at/}).last().click();
  await expect.poll(async () => video.evaluate(v => Math.abs(v.getBoundingClientRect().top))).toBeLessThan(2);
  expect(await video.evaluate((v: HTMLVideoElement) => v.paused)).toBe(true);
  expect(errors).toEqual([]);
});
