import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFileSync, readdirSync, existsSync } from 'node:fs';

test('analysis switches default to the focused rally test and enforce dependencies', async ({ page, request }) => {
  const file = readdirSync('.').find(name => name.endsWith('350_434.mp4'));
  test.skip(!file, 'Requires the specified Paris clip');
  await page.goto('/');
  await page.getByRole('button', { name: 'Upload Match', exact: true }).click();
  await page.getByLabel('Match video', { exact: true }).setInputFiles(file!);
  const options = page.getByRole('group', { name: 'Analysis options' });
  for (const label of ['YOLO player tracking', 'Shuttle tracking (TrackNet)', 'Ground segmentation and touch candidates', 'Body pose']) await expect(options.getByLabel(label, { exact: true })).toBeChecked();
  for (const label of ['Shot classification']) await expect(options.getByLabel(label, { exact: true })).not.toBeChecked();
  await expect(options.getByLabel('Near-player ending review')).not.toBeChecked();
  await options.getByLabel('Near-player ending review').check();
  for (const label of ['Body pose','Ground segmentation and touch candidates','Shuttle tracking (TrackNet)','YOLO player tracking']) await expect(options.getByLabel(label,{exact:true})).toBeChecked();
  await options.getByLabel('Shot classification').check();
  for (const label of ['Body pose', 'Shot classification', 'YOLO player tracking']) await expect(options.getByLabel(label, { exact: true })).toBeChecked();
  await options.getByLabel('YOLO player tracking').uncheck();
  for (const label of ['Body pose', 'Shot classification']) await expect(options.getByLabel(label, { exact: true })).not.toBeChecked();
  await expect(options.getByLabel('Near-player ending review')).not.toBeChecked();
  await options.getByLabel('Shuttle tracking (TrackNet)', { exact: true }).uncheck();
  await expect(options.getByLabel('Ground segmentation and touch candidates')).not.toBeChecked();
  await options.getByLabel('Ground segmentation and touch candidates').check();
  await expect(options.getByLabel('Shuttle tracking (TrackNet)', { exact: true })).toBeChecked();
  await options.getByLabel('YOLO player tracking').check();
  await expect(page.locator('.local-preview')).toHaveAttribute('aria-busy', 'false');
  await page.getByRole('button', { name: 'Analyze Shots & Rallies', exact: true }).click();
  const picker = page.locator('.corner-picker');
  const box = await picker.boundingBox(); expect(box).toBeTruthy();
  for (const [x,y] of [[461/1280,325/720],[817/1280,325/720],[999/1280,670/720],[284/1280,670/720]]) await picker.click({ position: { x: x*box!.width, y: y*box!.height } });
  let sent: unknown;
  await page.route('**/api/analysis', async route => {
    const body = new Request('http://localhost', { method: 'POST', headers: route.request().headers(), body: new Uint8Array(route.request().postDataBuffer()!) });
    sent = JSON.parse(String((await body.formData()).get('options')));
    await route.fulfill({ status: 422, json: { error: 'Options captured; no model run in this control test.' } });
  });
  await page.getByRole('button', { name: 'Analyze Shots & Rallies', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Options captured' })).toBeVisible();
  expect(sent).toEqual({ yolo: true, shuttle: true, ground: true, pose: false, shots: false, llm: false, ending:false });
  const invalid = await request.post('/api/analysis', { headers: { origin: 'http://127.0.0.1:3000' }, multipart: { video: { name: file!, mimeType: 'video/mp4', buffer: readFileSync(file!) }, corners: '[0.3,0.2,0.7,0.2,0.9,0.9,0.1,0.9]', options: JSON.stringify({ yolo:true, shuttle:false,ground:true,pose:false,shots:false,llm:false }) } });
  expect(invalid.status()).toBe(422);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  expect((await new AxeBuilder({ page }).include('.shot-upload-start').analyze()).violations).toEqual([]);
});

test('Paris 350_434 shows rally windows with LLM and contact extraction disabled', async ({ page, request }) => {
  test.skip(!existsSync('artifacts/paris434-job.json'), 'Requires the exact Paris tracking run');
  test.setTimeout(420_000);
  const manifest = JSON.parse(readFileSync('artifacts/paris434-job.json', 'utf8'));
  await expect.poll(async () => (await (await request.get(`/api/analysis/${manifest.id}`)).json()).status, { timeout: 390_000, intervals: [2000] }).toBe('complete');
  const result = (await (await request.get(`/api/analysis/${manifest.id}`)).json()).result;
  expect(result.fileName).toMatch(/350_434\.mp4$/);
  expect(result.options).toEqual(manifest.options);
  expect(result.shots).toEqual([]);
  expect(result.metrics.nearPoses + result.metrics.farPoses).toBe(0);
  expect(result.groundLanding.status).toBe('experimental');
  expect(result.groundLanding.candidates.map((item: { time: number }) => item.time)).toEqual([40.2,81.5]);
  expect(result.rallies.length).toBeGreaterThan(0);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(`/review/${manifest.id}`);
  await expect(page.getByRole('heading', { name: 'Review the rallies you lost.' })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Before-landing coaching' })).toHaveCount(0);
  await expect(page.getByRole('region', { name: 'Contact frame evidence' })).toHaveCount(0);
  await page.getByText('Technical details: shots, poses & rally boundaries',{exact:true}).click();
  await expect(page.getByRole('region',{name:'Possible shuttle landings'})).toHaveCount(0);
  const rallies = page.getByRole('region', { name: 'Rally windows' });
  await expect(rallies).toBeVisible();
  await expect(rallies.locator('select option')).toHaveCount(result.rallies.filter((r:{end:number|null})=>r.end!==null).length);
  await rallies.getByRole('button', { name: 'Replay this window' }).click();
  await expect.poll(() => page.locator('.review-camera video').evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(result.rallies.find((r:{end:number|null})=>r.end!==null).start);
  expect((await request.post(`/api/analysis/${manifest.id}/landing`, { headers: { origin: 'http://127.0.0.1:3000' }, data: { frame: 60 } })).status()).toBe(409);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download reviewed JSON' }).click();
  const exported = JSON.parse(readFileSync((await (await download).path())!, 'utf8'));
  expect(exported.options.llm).toBe(false);
  expect(exported.modelRallies).toEqual(result.rallies);
  expect((await new AxeBuilder({ page }).include('.analysis-review').analyze()).violations).toEqual([]);
  await page.screenshot({ path: 'artifacts/paris434-review.png', fullPage: true });
  expect(errors).toEqual([]);
});
