import type { EndingReview, ReviewData } from './analysis-review';
import type { MatchReportData, ReportAnswer } from './match-report';
import { attemptBones, attemptPhotoGeometry } from './attempt-photo';

export type ReportPhoto={rallyId:number;dataUrl:string;evidence:NonNullable<EndingReview['evidence']>;racket:[number,number]|null};
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const sections=(answer:ReportAnswer)=>Object.entries(answer).map(([key,value])=>`<section><h3>${escape(key[0].toUpperCase()+key.slice(1))}</h3><p>${escape(value)}</p></section>`).join('');

export function reportHtml(data:ReviewData,report:MatchReportData,photos:ReportPhoto[],labels:Record<number,string>) {
  const photo=(id:number)=>{
    const item=photos.find(p=>p.rallyId===id);if(!item)return '';
    if(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(item.dataUrl))throw new Error('Invalid report photo.');
    const {evidence:e}=item, point=item.racket ?? e.wristPoint;
    const x=point[0]*data.width,y=point[1]*data.height,sx=e.shuttlePoint[0]*data.width,sy=e.shuttlePoint[1]*data.height;
    const gap=Math.hypot(x-sx,y-sy).toFixed(1);
    const {person,left,top,width,height}=attemptPhotoGeometry(data,e,point);
    const pose=person?attemptBones.filter(([a,b])=>person.scores[a]>=.3&&person.scores[b]>=.3).map(([a,b])=>`<line x1="${person.landmarks[a][0]*data.width}" y1="${person.landmarks[a][1]*data.height}" x2="${person.landmarks[b][0]*data.width}" y2="${person.landmarks[b][1]*data.height}" stroke="#b9f58d" stroke-width="3"/>`).join(''):'';
    return `<figure><svg role="img" aria-label="Exact attempt frame ${e.frame} at ${e.time.toFixed(3)} seconds" viewBox="${left} ${top} ${width} ${height}"><image href="${item.dataUrl}" width="${data.width}" height="${data.height}"/>${pose}<g stroke="#ffbf69" stroke-width="4" fill="none"><path d="M${x},${y} L${sx},${sy}" stroke-dasharray="8 6"/><circle cx="${x}" cy="${y}" r="10"/><circle cx="${sx}" cy="${sy}" r="10"/></g><text x="${(x+sx)/2}" y="${Math.max(28,(y+sy)/2-15)}" text-anchor="middle" font-size="26" fill="white" stroke="#18251b" stroke-width="4" paint-order="stroke">${gap} px</text></svg><figcaption><strong>${e.time.toFixed(3)} s · frame ${e.frame}</strong><br>${item.racket?'Manually marked racket head':'Wrist proxy'} → tracked shuttle: ${gap} px in the original image, not a physical contact distance.<br>Selected for the smallest visible wrist-to-shuttle gap relative to player height within continuous tracking in the final two seconds. Not a confirmed racket-contact or first-ground-touch frame. Attached after generation; the report AI received text only.</figcaption></figure>`;
  };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>ShuttleSense — Match review</title><style>body{font:15px/1.7 system-ui,sans-serif;color:#20362c;max-width:960px;margin:auto;padding:32px}h1,h2,h3{line-height:1.3}h2{margin-top:32px;border-bottom:1px solid #cfdbd4;padding-bottom:8px}h3{font-size:16px}p{white-space:pre-line}.meta,figcaption{font-size:12px;color:#53635a;overflow-wrap:anywhere}.rally{display:flow-root}figure{float:left;width:280px;max-width:100%;margin:8px 24px 16px 0}svg{display:block;width:100%;height:auto;border-radius:8px}figcaption{margin-top:8px}@media(max-width:600px){body{padding:16px}figure{float:none;width:100%;margin:12px 0}}@media print{body{padding:0}figure{break-inside:avoid}h2,h3{break-after:avoid}}</style></head><body><header><p>SHUTTLESENSE · LOCAL AI REVIEW</p><h1>Match review</h1><p>${escape(data.fileName)}</p><p class="meta">Generated ${escape(report.generatedAt)} · ${escape(report.model)}<br>Evidence SHA256: ${escape(report.evidenceSha256)}</p><p>Experimental coaching from this recording only. Possible intent and reasons remain uncertain; this is not a verified assessment of the entire original match. Photos are local evidence illustrations, not model inputs.</p></header><h2>Recording overview</h2>${sections(report.answer)}${report.rallyReports.map(r=>`<article class="rally"><h2>${escape(labels[r.rallyId] ?? `Window ${r.rallyId}`)} · ${r.start.toFixed(3)}–${r.end.toFixed(3)} s</h2><p class="meta">Outcome: ${escape(r.outcome)}${r.outcome!=='unknown'?' · user marked':''}</p>${photo(r.rallyId)}${sections(r.answer)}</article>`).join('')}<footer><h2>Evidence and limits</h2><p>Exact named joint angles, pose timestamps, rally boundaries, tracking data, model provenance and actual text requests are available in the separate “Download AI evidence” JSON appendix. Camera-dependent 2D angles and wrist proxies do not prove shot type, intent, first ground touch or failure cause. Use your browser’s Print command to save this illustrated report as PDF.</p></footer></body></html>`;
}
