const assert=require('node:assert/strict');
const {chromium}=require('@playwright/test');
(async()=>{
 const browser=await chromium.launch({channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1280,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8004/review.html');
 await page.waitForFunction(()=>document.querySelector('video').readyState>=2);
 const duration=await page.locator('video').evaluate(v=>v.duration);
 assert(Math.abs(duration-15)<.1);
 await page.getByRole('button',{name:'62.23s near: smash (outside_play)',exact:true}).click();
 await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.paused&&v.currentTime>=2&&v.currentTime<3.5});
 await page.waitForFunction(()=>document.querySelector('video').paused,{timeout:5000});
 const stopped=await page.locator('video').evaluate(v=>v.currentTime);
 assert(stopped>=3.3&&stopped<3.7);
 assert.match(await page.locator('#pose').innerText(),/Elbow L \/ R/);
 assert.equal(await page.locator('figure img').count(),2);
 assert.equal(await page.getByRole('button',{name:/Possible rally/}).count(),0);
 await page.getByRole('button',{name:'Play full clip',exact:true}).click();
 await page.waitForFunction(()=>{const v=document.querySelector('video');return !v.paused&&v.currentTime<2});
 await page.locator('video').evaluate(v=>{v.pause();v.currentTime=2.6});
 await page.waitForFunction(()=>!document.querySelector('video').seeking);
 await page.screenshot({path:'artifacts/tracked-pose-rally-review.png',fullPage:true});
 const range=await page.request.get('http://127.0.0.1:8004/source.mp4',{headers:{Range:'bytes=100-199'}});
 assert.equal(range.status(),206);assert.equal((await range.body()).length,100);
 assert.equal((await page.request.get('http://127.0.0.1:8004/AGENTS.md')).status(),404);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({duration,boundedHitReplayEnd:stopped,byteRange:206,pageErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
